### PR TITLE
add .amlignore to not include local.py in AML snapshot

### PR DESCRIPTION
**Pull request by karolzak**
Just adding `.amlignore` under `example_experiment` dir and inside the `experiment_template.zip` to make sure local.py wouldn't go into AML snapshot when submitting a job.
Solves #13

### CODE REVIEW

**Comment by bepuca** [comment]
Hey @karolzak ! Looks good but the new zip file is storing the `printer.py` instead of a symlink to the `common` folder. There are some nuances on how to zip to keep that working well. I tried to have a look but I am limited on time and could not remember how to get it right. I can keep looking next week.

**Comment by karolzak** [comment]
@bepuca interesting, I'm pretty sure I didn't even unzip but just added `.amlignore` to the existing zip from the repo. Let me know if you find out what I'm missing

**Comment by bepuca** [comment]
The functionality has been added separately. The zip problems were fixed by using a hidden folder instead of a zip file for the experiment template.

**Comment by bepuca** [comment]
The functionality has been added separately. The zip problems were fixed by using a hidden folder instead of a zip file for the experiment template.

**Pull request closed without merging**
